deploy:
  tasks:
    - name: Copy files to deployment path
      command: /bin/cp -R * /home/radiantn/public_html/public/index.php

    - name: Move to project directory
      command: cd /home/radiantn/public_html/public

    - name: Update composer dependencies
      command: composer update
